ship/ship/urls.py
from django.conf.urls import url
from . import views

app_name = 'ship'

urlpatterns = [
    # /ship/
    url(r'^$', views.index, name='index'),

    # /ship/<department.id>/
    url(r'^(?P<department_id>[0-9]+)/$', views.detail, name='detail'),

    # /ship/<department.id>/
    url(r'^(?P<department_id>[0-9]+)/baknaz_team/$', views.baknaz_team, name='baknaz_team'),
]

ship/urls.py
from django.conf.urls import url
from . import views

app_name = 'ship'

urlpatterns = [
    # /ship/
    url(r'^$', views.index, name='index'),

    # /ship/<department.id>/
    url(r'^(?P<department_id>[0-9]+)/$', views.detail, name='detail'),

    # /ship/<department.id>/
    url(r'^(?P<department_id>[0-9]+)/baknaz_team/$', views.baknaz_team, name='baknaz_team'),

    # /ship/
    # url(r'^$', views.records, name='records'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ship/', include('ship.urls')),

]

ship/models.py
from django.db import models
import datetime
# import time


class Department(models.Model):
    officer = models.CharField(max_length=250)
    department_name = models.CharField(max_length=500)
    # genre = models.CharField(max_length=100)
    department_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.department_name + ' - ' + self.officer


class Soldier(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    tag = models.CharField(max_length=250, default="0x00 0x00 0x00 0x00")
    soldier_name = models.CharField(max_length=250)
    is_baknaz_team = models.BooleanField(default=False)

    def __str__(self):
        return self.soldier_name


class RecordManager(models.Manager):
    def create_singlerecord(self, compartment, tag_string):
        time_tag = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        singlerecord = self.create(compartment=compartment, tag_string=tag_string, time_stamp=time_tag)
        # time.sleep(1)  ------- not working!!
        return singlerecord


class SingleRecord(models.Model):
    time_stamp = models.CharField(max_length=250)
    tag_string = models.CharField(max_length=250, default="0x00 0x00 0x00 0x00")
    compartment = models.IntegerField(default=532)
    objects = RecordManager()

ship/ship/models.py
from django.db import models
from datetime import datetime


class Department(models.Model):
    officer = models.CharField(max_length=250)
    department_name = models.CharField(max_length=500)
    # genre = models.CharField(max_length=100)
    department_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.department_name + ' - ' + self.officer


class Soldier(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    tag = models.IntegerField()
    soldier_name = models.CharField(max_length=250)
    is_baknaz_team = models.BooleanField(default=False)

    def __str__(self):
        return self.soldier_name


class SingleRecord(models.Model):
    time_stamp = models.DateTimeField(auto_now_add=True, blank=True)
    tag_string = models.CharField(max_length=250, default="0x00 0x00 0x00 0x00")
    compartment = models.IntegerField(default=532)
    # soldier_tag_field_0 = models.IntegerField(default=0)
    # soldier_tag_field_1 = models.IntegerField(default=0)
    # soldier_tag_field_2 = models.IntegerField(default=0)
    # soldier_tag_field_3 = models.IntegerField(default=0)

ship/ship/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Department, Soldier


def index(request):
    all_departments = Department.objects.all()
    return render(request, 'ship/index.html', {'all_departments': all_departments})


def detail(request, department_id):
    # album = Album.objects.get(pk=department_id)
    department = get_object_or_404(Department, pk=department_id)
    return render(request, 'ship/detail.html',{ 'department': department,})


def baknaz_team(request, department_id):
    department = get_object_or_404(Department, pk=department_id)
    try:
        selected_soldier=department.soldier_set.get(pk=request.POST['soldier'])
    except(KeyError, Soldier.DoesNotExist):
        return render(request, 'ship/detail.html',
                      {'department': department, 'error_message': "You did not select a valid soldier"})
    else:
        selected_soldier.is_baknaz_team=True
        selected_soldier.save()
        return render(request, 'ship/detail.html', {'department': department, })

ship/views.py
# from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Department, Soldier, SingleRecord


def index(request):
    all_departments = Department.objects.all()
    all_records = SingleRecord.objects.all()
    return render(request, 'ship/index.html', {'all_departments': all_departments, 'all_records': all_records})


def detail(request, department_id):
    department = get_object_or_404(Department, pk=department_id)
    return render(request, 'ship/detail.html', {'department': department, })


def baknaz_team(request, department_id):
    department = get_object_or_404(Department, pk=department_id)
    try:
        selected_soldier = department.soldier_set.get(pk=request.POST['soldier'])
    except(KeyError, Soldier.DoesNotExist):
        return render(request, 'ship/detail.html',
                      {'department': department, 'error_message': "You did not select a valid soldier"})
    else:
        selected_soldier.is_baknaz_team = True
        selected_soldier.save()
        return render(request, 'ship/detail.html', {'department': department, })


# def records(request):
#     all_records = SingleRecord.objects.all()
#     return render(request, 'ship/index.html', {'all_records': all_records})

ship/ship/templates/ship/detail.html
<img src="{{ department.department.logo }}">

<h1> {{ department.department_name }}</h1>
<h2>{{ department.officer }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action ="{% url 'ship:baknaz_team' department.id %}" method="post" >
    {% csrf_token %}
    {% for soldier in department.soldier_set.all %}
        <input type="radio" id="soldier{{ forloop.counter }}" name="soldier" value="{{ soldier.id }}">
        <label for="soldier{{ forloop.counter }}">
        {{ soldier.soldier_name }}
        {{ soldier.rank }}
        {%  if soldier.is_baknaz_team %}
            <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}
        </label><br>
    {% endfor %}
   <input type="submit" value="Baknaz_team">
</form>














ship/ship/templates/ship/index.html
<!-- Loads the path to your static files-->
{%  load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'ship/style.css' %}" />

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--logo -->
        <div class=navbar-header">
            <a class="navbar-brand" href="{% url 'ship:index' %}">big-brother</a>

        </div>
    </div>

</nav>
{% if all_departments %}

    <h3>Here are the ship departments</h3>
    <ul>
        {% for department in all_departments %}
        <li><a href="{% url 'ship:detail' department.id %}">{{ department.department_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
<h3>no departments in database</h3>
{% endif %}

ship/templates/ship/detail.html
<img src="{{ department.department_logo }}">

<h1> {{ department.department_name }}</h1>
<h2>{{ department.officer }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action ="{% url 'ship:baknaz_team' department.id %}" method="post" >
    {% csrf_token %}
    {% for soldier in department.soldier_set.all %}
        <input type="radio" id="soldier{{ forloop.counter }}" name="soldier" value="{{ soldier.id }}">
        <label for="soldier{{ forloop.counter }}">
        {{ soldier.soldier_name }}
        {{ soldier.rank }}
        {%  if soldier.is_baknaz_team %}
            <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}
        </label><br>
    {% endfor %}
   <input type="submit" value="Baknaz_team">
</form>














ship/templates/ship/index.html
<!-- Loads the path to your static files-->
{%  load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'ship/style.css' %}" />

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--logo -->
        <div class=navbar-header">
            <a class="navbar-brand" href="{% url 'ship:index' %}">ship</a>
{#            <a class="navbar-brand" href="{% url 'ship:records' %}">records</a>#}

        </div>
    </div>

</nav>
{% if all_departments %}

    <h1>Here are the ship departments</h1>
    <ul>
        {% for department in all_departments %}
        <li><a href="{% url 'ship:detail' department.id %}">{{ department.department_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
<h3>no departments in database</h3>
{% endif %}

{% if all_records %}

    <h1>Here are all the ship records</h1>
    <ul>
        {% for singlerecord in all_records %}
        <li>{{ singlerecord.tag_string}}, {{singlerecord.time_stamp}}, {{singlerecord.compartment }}</li>
        {% endfor %}
    </ul>
{% else %}
<h3>no records in database</h3>
{% endif %}

ship/templates/ship/records.html
{#<!-- Loads the path to your static files-->#}
{#{%  load staticfiles %}#}
{#<link rel="stylesheet" type="text/css" href="{% static 'ship/style.css' %}" />#}
{##}
{#<nav class="navbar navbar-inverse">#}
{#    <div class="container-fluid">#}
{##}
{#        <!--logo -->#}
{#        <div class=navbar-header">#}
{#            <a class="navbar-brand" href="{% url 'ship:index' %}">ship</a>#}
{#            <a class="navbar-brand" href="{% url 'ship:records' %}">records</a>#}
{#        </div>#}
{#    </div>#}
{##}
{#</nav>#}
{#{% if all_records %}#}
{##}
{#    <h3>Here are all the ship records</h3>#}
{#    <ul>#}
{#        {% for singlerecord in all_records %}#}
{#        <li><a href="{% url 'ship:records' singlerecord.id %}">{{ singlerecord.tag_string}}, {{singlerecord.time_stamp}}, {{singlerecord.compartment }}</a></li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% else %}#}
{#<h3>no records in database</h3>#}
{#{% endif %}#}